version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.47.0
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Add musl target
          command: rustup target add x86_64-unknown-linux-musl
      - run:
          name: Build
          command: cargo build --verbose
      - run:
          name: Build release
          command: |
            cargo build --release --target=x86_64-unknown-linux-musl
            strip --strip-unneeded target/x86_64-unknown-linux-musl/release/zip2zstd
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/zip2zstd
          destination: zip2zstd

workflows:
  version: 2.1

  build:
    jobs:
      - build
